### ISSUE TITLE
KeyError when calling `map_ecotopes()` on example data

### ISSUE THREAD

**Issue by svenvanderburg** [ghendrickx/EMMA#50]
When running `map_ecotopes()` on the example data (https://github.com/ghendrickx/EMMA/blob/master/examples/ex_map_data/output_map.nc) I got the following error:

```python
KeyError: "No variable named 'mesh2d_face_x'. Variables on the dataset include ['FlowElem_xcc', 'FlowElem_ycc', 'waterdepth', 'ucx', 'ucy', 'sa1']"
```

**Comment by ghendrickx** [comment]
The wrong map-configuration was set as default, this has been resolved (c9e51470da12c593bc9cb8a7370ceda507069194).
